# Generated by Django 5.1.3 on 2024-12-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriterioInclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rampas_acceso", models.BooleanField(default=False)),
                ("elevadores", models.BooleanField(default=False)),
                ("banos_accesibles", models.BooleanField(default=False)),
                ("espacios_trabajo_adaptados", models.BooleanField(default=False)),
                ("politica_inclusion_laboral", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("public", "Publico"), ("private", "Privada")],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=15)),
                ("correo_contacto", models.EmailField(max_length=254)),
                ("criterios_inclusion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_puesto", models.TextField()),
                ("cargo", models.CharField(max_length=100)),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("advertencias", models.TextField(blank=True, null=True)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("remoto", "Remoto"),
                            ("hibrido", "Hibrido"),
                        ],
                        default="presencial",
                        max_length=50,
                    ),
                ),
                ("fecha_publicacion", models.DateField()),
                ("fecha_cierre", models.DateField()),
                (
                    "criterio_inclusion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="formulario.criterioinclusion",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicaciones",
                        to="formulario.empresa",
                    ),
                ),
            ],
        ),
    ]
