# Generated by Django 5.1.3 on 2024-12-04 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Publicacion",
            new_name="Oferta",
        ),
    ]
