# Generated by Django 5.1.3 on 2024-12-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0003_remove_criterioinclusion_banos_accesibles_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criterioinclusion",
            options={
                "verbose_name": "Criterio de Inclusion",
                "verbose_name_plural": "Criterios de Inclusion",
            },
        ),
        migrations.RemoveField(
            model_name="oferta",
            name="criterio_inclusion",
        ),
        migrations.AddField(
            model_name="oferta",
            name="criterio_inclusion",
            field=models.ManyToManyField(
                blank=True, null=True, to="formulario.criterioinclusion"
            ),
        ),
    ]
